[env:esp32dev]
platform = espressif32 @ 5.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<*.cpp> +<cuckoo_filter/*.cpp> +<websocket/*.cpp>
lib_deps = 
    links2004/WebSockets @ ^2.3.7
    bblanchon/ArduinoJson @ ^6.21.0